## General
model: 'yolov3-config.json'
labels: ['person', 'dog', 'car']
img_dim: 416 # must be a multiple of 32
device: 'cpu'
version: 0.1

## Training hyper-parameters
epochs: 10 # tbd
batch_size: 64
subdivisions: 16
learning_rate: 0.001
lr_decay: 0.8
decay: 0.0005
confidence_thres: 0.5
nms_thres: 0.45
classes: 80
channels: 3
bn_momentum: 0.9
