model: 'yolov3.json'
labels: []
img_width: 416
img_height: 416

epochs: 1
batch_size: 32
learning_rate: 0.001
decay: 0.0005
confidence_thres: 0.5
nms_thres: 0.4
classes: 80
channels: 3
bn_momentum: 0.9
